include_guard(GLOBAL)

set(VKSPLAT_VULKAN_HEADERS_VERSION 1.4.350.0)
set(VKSPLAT_VULKAN_HEADERS_ARCHIVE "${CMAKE_CURRENT_LIST_DIR}/../contrib/Vulkan-Headers-vulkan-sdk-${VKSPLAT_VULKAN_HEADERS_VERSION}.tar.gz")
set(VKSPLAT_VULKAN_HEADERS_REMOTE_URL
    "https://github.com/KhronosGroup/Vulkan-Headers/archive/vulkan-sdk-${VKSPLAT_VULKAN_HEADERS_VERSION}/Vulkan-Headers-vulkan-sdk-${VKSPLAT_VULKAN_HEADERS_VERSION}.tar.gz"
)
set(VKSPLAT_VULKAN_HEADERS_SHA256 "SHA256=70270d10bf2c1e074a06ee37a50b75d332993d1b80a1d9526eeed2da6d82ed22")

vksplat_fetch_dependency(
    NAME vulkan_headers
    URL "${VKSPLAT_VULKAN_HEADERS_REMOTE_URL}"
    LOCAL_ARCHIVE "${VKSPLAT_VULKAN_HEADERS_ARCHIVE}"
    URL_HASH "${VKSPLAT_VULKAN_HEADERS_SHA256}"
)
