include_guard(GLOBAL)

set(VKSPLAT_NLOHMANN_JSON_VERSION 3.11.3)
set(VKSPLAT_NLOHMANN_JSON_ARCHIVE
    "${CMAKE_CURRENT_LIST_DIR}/../contrib/json-v${VKSPLAT_NLOHMANN_JSON_VERSION}.tar.gz"
)
set(VKSPLAT_NLOHMANN_JSON_REMOTE_URL
    "https://github.com/nlohmann/json/archive/refs/tags/v${VKSPLAT_NLOHMANN_JSON_VERSION}.tar.gz"
)
set(VKSPLAT_NLOHMANN_JSON_SHA256 "SHA256=0d8ef5af7f9794e3263480193c491549b2ba6cc74bb018906202ada498a79406")

set(JSON_BuildTests OFF CACHE INTERNAL "")

vksplat_fetch_dependency(
    NAME nlohmann_json
    URL "${VKSPLAT_NLOHMANN_JSON_REMOTE_URL}"
    LOCAL_ARCHIVE "${VKSPLAT_NLOHMANN_JSON_ARCHIVE}"
    URL_HASH "${VKSPLAT_NLOHMANN_JSON_SHA256}"
)
